# Save as .codeclimate.yml (note leading .) in project root directory
languages:
  JavaScript: true
  PHP: true
exclude_paths:
- "lib"
- "app/Test"
- "app/Plugin/Admin/webroot/js/ext/"
- "app/Plugin/Admin/webroot/js/jqsuite"
