language: php

php:
  - 5.3

env:
  - DB=mysql

before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE teslacollection_com;'; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql teslacollection_com < ddl/teslacollection_com.sql; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE teslacollection_com_test;'; fi"
  - mkdir -p ./app/tmp/cache/models
  - mkdir -p ./app/tmp/cache/persistent
  - chmod -R 777 ./app/tmp
  - cp app/Config/core_default.php app/Config/core.php
  - which composer
  - cd app
  - composer install
  - cd ..
  - phpenv rehash
  - set +H
  - echo "<?php
    class DATABASE_CONFIG {
    public \$default = array(
      'persistent' => false,
      'host' => '',
      'login' => '',
      'password' => '',
      'database' => 'teslacollection_com',
      'prefix' => ''
    );
    public \$test = array(
      'persistent' => false,
      'host' => '',
      'login' => '',
      'password' => '',
      'database' => 'teslacollection_com_test',
      'prefix' => ''
    );
    }" > app/Config/database.php

script:
  - app/Console/cake test app AllTests --debug

notifications:
  email: true
