language: php

php:
  - 5.3

env:
  - DB=mysql

matrix:
  include:
    - php: 5.3

before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE teslacollection_com;'; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE teslacollection_com_test;'; fi"
  - chmod -R 777 ./app/tmp
  - phpenv rehash
  - set +H
  - echo "<?php
    class DATABASE_CONFIG {
    public \$default = array(
      'persistent' => false,
      'host' => '',
      'login' => '',
      'password' => '',
      'database' => 'teslacollection_com',
      'prefix' => ''
    );
    public \$test = array(
      'persistent' => false,
      'host' => '',
      'login' => '',
      'password' => '',
      'database' => 'teslacollection_com_test',
      'prefix' => ''
    );
    }" > app/Config/database.php

script:
  - sh -c "app/Console/cake test app AllTests --stderr"

notifications:
  email: true
